language: csharp
solution: "./ZbW.Testing.Dms_Aufgabe/ZbW.Testing.Dms.sln"
install:
  - nuget restore ./ZbW.Testing.Dms_Aufgabe/ZbW.Testing.Dms.sln
  - nuget install NUnit.Console -Version 3.11.0 -OutputDirectory testrunner
script:
- xbuild ./ZbW.Testing.Dms_Aufgabe/ZbW.Testing.Dms.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.11.0/tools/nunit3-console.exe ./ZbW.Testing.Dms_Aufgabe/ZbW.Testing.Dms.Client.UnitTests/bin/Debug/ZbW.Testing.Dms.Client.UnitTests.dll